export const PORT = process.env.PORT || 4000
export const HTTP_URL = process.env.HTTP_URL || 'https://myecoapp-deploy.vercel.app/';
export const JWT_SECRET = process.env.JWT_SECRET
export const JWT_EXPIRY = process.env.JWT_EXPIRY
export const VERIFICATION_URL = process.env.VERIFICATION_URL
export const VERIFY_EMAIL = process.env.VERIFY_EMAIL
export const VERIFY_PASS = process.env.VERIFY_PASS
export const RESET_PASS_URL = process.env.RESET_PASS_URL
export const RESET_EMAIL = process.env.RESET_EMAIL
export const RESET_PASS = process.env.RESET_PASS
